---
title: "UGA_REACH_Phone_inventory"
author: "Amos Nyarwaya"
date: "7/13/2022"
output: 
   html_document:
     toc: true
     toc_float:
       collapsed: false
       smooth_scroll: false
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding, output_file = paste0(dirname(inputFile), '/assets_inventory_report_', format(Sys.Date(), '%Y_%m_%d'),'.html')) }) 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F)

library(tidyverse)
library(lubridate)
library(glue)

# read data
df_assets_data <- readxl::read_excel("../inputs/REACH_UGA_Phone_inventory_tool_Finalized_Data.xlsx") %>% 
  mutate(uuid = `_uuid`,
         start_date = as_date(start),
         start = as_datetime(start),
         end = as_datetime(end))

```

## Number of items by type

```{r, echo = FALSE}
df_assets_data %>% 
   group_by(item_type) %>% 
   summarise(number_of_items = n()) %>% 
   DT::datatable()
```


## Number of items by type and brand

```{r, echo = FALSE}
df_assets_data %>% 
   group_by(item_type, item_brand) %>% 
   summarise(number_of_items = n()) %>% 
   DT::datatable()
```

## Number of items by type brand and model

```{r, echo = FALSE}
df_assets_data %>% 
   group_by(item_type, item_brand, item_model) %>% 
   summarise(number_of_items = n()) %>% 
   DT::datatable()
```

<!-- ## Item physical appearance by type -->

<!-- ```{r, echo = FALSE} -->
<!-- df_assets_data %>%  -->
<!--    group_by(item_type, phy_app) %>%  -->
<!--    summarise(number_of_items = n()) %>%  -->
<!--    DT::datatable() -->
<!-- ``` -->

<!-- ## Item physical appearance by type and brand -->

<!-- ```{r, echo = FALSE} -->
<!-- df_assets_data %>%  -->
<!--    group_by(item_type, item_brand, phy_app) %>%  -->
<!--    summarise(number_of_items = n()) %>%  -->
<!--    DT::datatable() -->
<!-- ``` -->

<!-- ## Item physical appearance by type -->

## Number of items by state

```{r, echo = FALSE}
df_assets_data %>%
   group_by(item_type, item_state) %>%
   summarise(number_of_items = n()) %>%
   DT::datatable()
```

## Number of items by state_observe

```{r, echo = FALSE}
df_assets_data %>%
   group_by(item_type, item_state_observe) %>%
   summarise(number_of_items = n()) %>%
   DT::datatable()
```

## Maps.me functionality of the item

```{r, echo = FALSE}
df_assets_data %>%
   group_by(item_type, maps_me_funct) %>%
   summarise(number_of_items = n()) %>%
   DT::datatable()
```

## Item screen touch functionality

```{r, echo = FALSE}
df_assets_data %>%
   group_by(item_type, screen_touch, screen_touch_observe) %>%
   summarise(number_of_items = n()) %>%
   DT::datatable()
```

<!-- ## Item screen touch observe -->

<!-- ```{r, echo = FALSE} -->
<!-- df_assets_data %>% -->
<!--    group_by(item_type, screen_touch_observe) %>% -->
<!--    summarise(number_of_items = n()) %>% -->
<!--    DT::datatable() -->
<!-- ``` -->

## Item battery functionality

```{r, echo = FALSE}
df_assets_data %>%
   group_by(item_type, battery, battery_observe) %>%
   summarise(number_of_items = n()) %>%
   DT::datatable()
```

## Item internet functionality

```{r, echo = FALSE}
df_assets_data %>%
   group_by(item_type, internet, internet_observe) %>%
   summarise(number_of_items = n()) %>%
   DT::datatable()
```

## Item GPS functionality

```{r, echo = FALSE}
df_assets_data %>%
   group_by(item_type, gps_function, gps_funct) %>%
   summarise(number_of_items = n()) %>%
   DT::datatable()
```



